apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    model.platform/version: {{ .Values.model.version | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        model.platform/version: {{ .Values.model.version | quote }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uvicorn"]
          args: ["rental_mlops.serving:create_app", "--factory", "--host", "0.0.0.0", "--port", {{ .Values.service.targetPort | quote }}]
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MODEL_ARTIFACT_PATH
              value: {{ .Values.model.artifactPath | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
